### ISSUE TITLE
AccessViolationException when scrolling too fast on a custom VirtualizingLayout

### ISSUE THREAD

**Issue by azchohfi** [microsoft/CsWinRT#547] opened 2020-10-28 18:44 UTC
This happens when scrolling too fast on a StaggeredLayout (https://github.com/windows-toolkit/WindowsCommunityToolkit/blob/winui/Microsoft.Toolkit.Uwp.UI.Controls.Layout/StaggeredLayout/StaggeredLayout.cs#L233).

System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

```
 	ntdll.dll!00007ffd15f769a4()	Unknown
 	KernelBase.dll!00007ffd13af118e()	Unknown
 	ntdll.dll!00007ffd15f7b81f()	Unknown
 	ntdll.dll!00007ffd15f021d0()	Unknown
 	ntdll.dll!00007ffd15f7a82e()	Unknown
 	KernelBase.dll!00007ffd13b0b153()	Unknown
 	combase.dll!00007ffd156ca548()	Unknown
 	Microsoft.ui.xaml.dll!DirectUI::PropertyProviderPropertyAccess::TryReconnect(IInspectable * pSource, unsigned char fListenToChanges, unsigned char & bConnected, const CClassInfo * & pResolvedType) Line 172	C++
 	Microsoft.ui.xaml.dll!DirectUI::PropertyAccessPathStep::ConnectPropertyAccessForObject(IInspectable * pSource, unsigned int fListenToChanges, unsigned char * pbConnected) Line 233	C++
 	Microsoft.ui.xaml.dll!DirectUI::PropertyAccessPathStep::ConnectToPropertyOnSource(IInspectable * pSource, unsigned int fListenToChanges) Line 156	C++
 	Microsoft.ui.xaml.dll!DirectUI::PropertyAccessPathStep::ReConnect(IInspectable * pSource) Line 36	C++
 	Microsoft.ui.xaml.dll!DirectUI::PropertyPathListener::ConnectPathStep(DirectUI::PropertyPathStep * pStep, IInspectable * pSource) Line 81	C++
 	Microsoft.ui.xaml.dll!DirectUI::PropertyPathListener::SetSource(IInspectable * pSource) Line 60	C++
 	Microsoft.ui.xaml.dll!DirectUI::BindingExpression::ConnectToEffectiveSource() Line 1259	C++
 	Microsoft.ui.xaml.dll!DirectUI::BindingExpression::RefreshBindingValue() Line 1327	C++
 	Microsoft.ui.xaml.dll!DirectUI::BindingExpression::BindingSourceChanged() Line 1309	C++
 	Microsoft.ui.xaml.dll!DirectUI::BindingExpression::DataContextChanged(const DirectUI::DataContextChangedParams * pArgs) Line 1692	C++
 	Microsoft.ui.xaml.dll!DirectUI::BindingExpressionDataContextChangedHandler::Invoke(DirectUI::DependencyObject * pSender, const DirectUI::DataContextChangedParams * pArgs) Line 445	C++
 	Microsoft.ui.xaml.dll!DirectUI::CEventSourceBase<DirectUI::IDataContextChangedEventSource,DirectUI::IDataContextChangedHandler,DirectUI::DependencyObject,DirectUI::DataContextChangedParams const>::Raise(DirectUI::DependencyObject * pSource, const DirectUI::DataContextChangedParams * pArgs) Line 306	C++
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkElement::NotifyBindingExpressions(const DirectUI::DataContextChangedParams & args) Line 662	C++
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkElement::NotifyOfDataContextChange(const DirectUI::DataContextChangedParams & args) Line 448	C++
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkElement::OnAncestorDataContextChanged(const DirectUI::DataContextChangedParams & args) Line 799	C++
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkElement::PropagateDataContextChanged(const DirectUI::DataContextChangedParams & args) Line 756	C++
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkElement::NotifyOfDataContextChange(const DirectUI::DataContextChangedParams & args) Line 495	C++
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkElement::OnPropertyChanged2(const PropertyChangedParams & args) Line 580	C++
 	Microsoft.ui.xaml.dll!DirectUI::DependencyObject::NotifyPropertyChanged(const PropertyChangedParams & args) Line 2240	C++
 	[Inline Frame] Microsoft.ui.xaml.dll!DirectUI::DependencyObject::NotifyPropertyChanged(CDependencyObject *) Line 2661	C++
 	[Inline Frame] Microsoft.ui.xaml.dll!CFxCallbacks::DependencyObject_NotifyPropertyChanged(CDependencyObject *) Line 606	C++
 	[Inline Frame] Microsoft.ui.xaml.dll!CDependencyObject::NotifyPropertyChanged(const PropertyChangedParams &) Line 2823	C++
 	Microsoft.ui.xaml.dll!CDependencyObject::SetEffectiveValue(const CDependencyObject::EffectiveValueParams & args) Line 1636	C++
 	Microsoft.ui.xaml.dll!CDependencyObject::UpdateEffectiveValue(const CDependencyObject::UpdateEffectiveValueParams & args) Line 1902	C++
 	Microsoft.ui.xaml.dll!CDependencyObject::SetValue(const SetValueParams & args) Line 1668	C++
 	Microsoft.ui.xaml.dll!CUIElement::SetValue(const SetValueParams & args) Line 703	C++
 	Microsoft.ui.xaml.dll!CFrameworkElement::SetValue(const SetValueParams & args) Line 235	C++
 	Microsoft.ui.xaml.dll!CPanel::SetValue(const SetValueParams & args) Line 104	C++
 	[Inline Frame] Microsoft.ui.xaml.dll!DependencyObject_SetValue(CDependencyObject *) Line 2217	C++
 	[Inline Frame] Microsoft.ui.xaml.dll!DirectUI::DependencyObject::SetValueCore(const SetValueParams &) Line 1034	C++
 	Microsoft.ui.xaml.dll!DirectUI::DependencyObject::SetValueCore(const CDependencyProperty * dp, IInspectable * value, bool setEffectiveValueOnly, BaseValueSource baseValueSource) Line 1372	C++
 	[Inline Frame] Microsoft.ui.xaml.dll!DirectUI::DependencyObject::SetValueCore(const CDependencyProperty *) Line 247	C++
 	Microsoft.ui.xaml.dll!DirectUI::DependencyObject::SetValueByKnownIndex(KnownPropertyIndex nPropertyIndex, IInspectable * pValue) Line 1107	C++
 	Microsoft.UI.Xaml.Controls.dll!00007ffcabac39ba()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!00007ffcaba68846()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!00007ffcaba68650()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!00007ffcaba77448()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!00007ffcabab3d90()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!00007ffcabc9130f()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!00007ffcabc6d007()	Unknown
 	[Managed to Native Transition]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.Controls.IVirtualizingLayoutContext.Microsoft.UI.Xaml.Controls.IVirtualizingLayoutContext.GetOrCreateElementAt(int index)	Unknown
>	Microsoft.Toolkit.Uwp.UI.Controls.Layout.dll!Microsoft.Toolkit.Uwp.UI.Controls.StaggeredLayout.MeasureOverride(Microsoft.UI.Xaml.Controls.VirtualizingLayoutContext context, Windows.Foundation.Size availableSize) Line 233	C#
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.Controls.IVirtualizingLayoutOverrides.Do_Abi_MeasureOverride_2(System.IntPtr thisPtr, System.IntPtr context, Windows.Foundation.Size availableSize, Windows.Foundation.Size* result)	Unknown
 	[Native to Managed Transition]	
 	Microsoft.UI.Xaml.Controls.dll!00007ffcaba541cc()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!00007ffcaba570c2()	Unknown
 	Microsoft.UI.Xaml.Controls.dll!00007ffcaba76f1c()	Unknown
 	[Inline Frame] Microsoft.ui.xaml.dll!DirectUI::FrameworkElementGenerated::MeasureOverrideProtected(ABI::Windows::Foundation::Size) Line 1029	C++
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkElement::MeasureOverrideFromCore(CFrameworkElement * nativeTarget, float inWidth, float inHeight, float * outWidth, float * outHeight) Line 246	C++
 	[Inline Frame] Microsoft.ui.xaml.dll!CFxCallbacks::FrameworkElement_MeasureOverride(CFrameworkElement *) Line 753	C++
 	Microsoft.ui.xaml.dll!CFrameworkElement::MeasureCore(XSIZEF availableSize, XSIZEF & desiredSize) Line 1573	C++
 	Microsoft.ui.xaml.dll!CUIElement::MeasureInternal(XSIZEF availableSize) Line 3977	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3837	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CUIElement::Measure(XSIZEF availableSize) Line 3887	C++
 	Microsoft.ui.xaml.dll!CLayoutManager::UpdateLayout(unsigned int controlWidth, unsigned int controlHeight) Line 278	C++
 	Microsoft.ui.xaml.dll!CCoreServices::NWDrawTree(HWWalk * pHWWalk, CWindowRenderTarget * pRenderTarget, VisualTree * pVisualTree, unsigned int forceRedraw, XRECT_WH * prcDirtyRect) Line 6100	C++
 	Microsoft.ui.xaml.dll!CCoreServices::NWDrawMainTree(CWindowRenderTarget * pIRenderTarget, bool fForceRedraw, XRECT_WH * prcDirtyRect) Line 5904	C++
 	Microsoft.ui.xaml.dll!CWindowRenderTarget::Draw(CCoreServices * fForceRedraw, unsigned int prcDirtyRect, XRECT_WH *) Line 132	C++
 	Microsoft.ui.xaml.dll!CXcpBrowserHost::OnTick() Line 345	C++
 	Microsoft.ui.xaml.dll!CXcpDispatcher::Tick() Line 1219	C++
 	Microsoft.ui.xaml.dll!CXcpDispatcher::OnReentrancyProtectedWindowMessage(HWND__ * msg, unsigned int lParam, unsigned __int64) Line 822	C++
 	[Inline Frame] Microsoft.ui.xaml.dll!CXcpDispatcher::ProcessMessage(HWND__ *) Line 694	C++
 	Microsoft.ui.xaml.dll!CXcpDispatcher::WindowProc(HWND__ * hwnd, unsigned int msg, unsigned __int64 wParam, __int64 lParam) Line 652	C++
 	Microsoft.ui.xaml.dll!CDeferredInvoke::DispatchQueuedMessage(bool * dispatchedWork, bool * hasMoreWork) Line 190	C++
 	[Inline Frame] Microsoft.ui.xaml.dll!CXcpDispatcher::MessageTimerCallback() Line 1300	C++
 	Microsoft.ui.xaml.dll!CXcpDispatcher::MessageTimerCallbackStatic(void * myUserData) Line 1292	C++
 	CoreMessagingXP.dll!00007ffce08e9ee8()	Unknown
 	CoreMessagingXP.dll!00007ffce08e9dbb()	Unknown
 	CoreMessagingXP.dll!00007ffce08c4b22()	Unknown
 	CoreMessagingXP.dll!00007ffce089d17e()	Unknown
 	CoreMessagingXP.dll!00007ffce088bfc9()	Unknown
 	CoreMessagingXP.dll!00007ffce089d9b3()	Unknown
 	CoreMessagingXP.dll!00007ffce08e657b()	Unknown
 	CoreMessagingXP.dll!00007ffce08e6611()	Unknown
 	CoreMessaging.dll!00007ffd105ca170()	Unknown
 	CoreMessaging.dll!00007ffd105ca0c1()	Unknown
 	CoreMessaging.dll!00007ffd105e78f8()	Unknown
 	CoreMessaging.dll!00007ffd105bc0f8()	Unknown
 	CoreMessaging.dll!00007ffd105b8510()	Unknown
 	CoreMessaging.dll!00007ffd105b81cc()	Unknown
 	CoreMessaging.dll!00007ffd105b7f30()	Unknown
 	user32.dll!00007ffd14b00089()	Unknown
 	user32.dll!00007ffd14affbfc()	Unknown
 	user32.dll!00007ffd14b15f8d()	Unknown
 	ntdll.dll!00007ffd15f7a7d4()	Unknown
 	win32u.dll!00007ffd13e21104()	Unknown
 	user32.dll!00007ffd14b15fee()	Unknown
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkApplication::ProcessEvents() Line 1158	C++
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkApplication::StartDesktop() Line 210	C++
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkApplicationFactory::Start(ABI::Microsoft::UI::Xaml::IApplicationInitializationCallback * pCallback) Line 713	C++
 	[Managed to Native Transition]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.IApplicationStatics.Microsoft.UI.Xaml.IApplicationStatics.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.Application.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback callback)	Unknown
 	Microsoft.Toolkit.Uwp.SampleApp.dll!Microsoft.Toolkit.Uwp.SampleApp.Program.Main(string[] args) Line 31	C#
 	[Native to Managed Transition]	
 	hostpolicy.dll!00007ffcec632722()	Unknown
 	hostpolicy.dll!00007ffcec632987()	Unknown
 	hostpolicy.dll!00007ffcec63338b()	Unknown
 	hostfxr.dll!00007ffcf0a839ea()	Unknown
 	hostfxr.dll!00007ffcf0a87358()	Unknown
 	hostfxr.dll!00007ffcf0a85b5f()	Unknown
 	hostfxr.dll!00007ffcf0a82029()	Unknown
 	Microsoft.Toolkit.Uwp.SampleApp.exe!00007ff773b9e090()	Unknown
 	Microsoft.Toolkit.Uwp.SampleApp.exe!00007ff773b9e3f8()	Unknown
 	Microsoft.Toolkit.Uwp.SampleApp.exe!00007ff773b9fee8()	Unknown
 	kernel32.dll!00007ffd14cf4ede()	Unknown
 	ntdll.dll!00007ffd15f27c6b()	Unknown

```

**Comment by AdamBraden** [comment] 2020-10-29 17:12
@azchohfi - can you load all symbols to get the native call stack? Looks like it might be a WinUI issue, but a native stack with symbols loaded can help us confirm.

**Comment by AdamBraden** [comment] 2020-10-29 17:13
Dupe of #550

**Closed by AdamBraden** 2020-10-29 17:13 UTC
