### ISSUE TITLE
Remove requirement of declaring all activatable classes for WinUI 3 apps

### ISSUE THREAD

**Issue by andrewleader** [microsoft/CsWinRT#925] opened 2021-07-25 17:21 UTC
## Summary
Having to declare activatable classes in the consuming app is a pain! There should be a way around it. When I create a new WinUI 3 C++ app and try to use a C# CsWinRT NuGet package, I have to declare all of the activatable classes before using them.

```
  <file name="WinRT.Host.dll">
    <activatableClass
        name="ClassLibrary1.Class1"
        threadingModel="both"
        xmlns="urn:schemas-microsoft-com:winrt.v1" />
    ...
  </file>
```

Otherwise, I get the Class not registered exceptions.

```
Exception thrown at 0x75E6E7A2 (KernelBase.dll) in App28.exe: WinRT originate error - 0x80040154 : 'Class not registered'.
Exception thrown at 0x75E6E7A2 in App28.exe: Microsoft C++ exception: winrt::hresult_class_not_registered at memory location 0x010FC38C.
Exception thrown at 0x75E6E7A2 in App28.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
```

There at least should be a way for a NuGet package author to include these class registrations so that consuming apps don't have to!

**Comment by angelazhangmsft** [comment] 2021-07-26 16:15
Dupe of #789 - thanks for the feedback Andrew!

**Closed** 2021-07-27 17:09 UTC
Labels: authoring, enhancement

**Comment by andrewleader** [comment] 2021-07-27 17:10
Thanks Angela! Btw I think I saw that existing issue but it didn't have any description or explanation so I wasn't sure it was the same thing... feel free to copy parts or all of this description into yours :) Glad it's already tracked :)
