### ISSUE TITLE
Windows.Foundation.Metadata.GuidAttribute' attribute for type 'System.CodeDom.Compiler.GeneratedCodeAttribute' not found

### ISSUE THREAD

**Issue by asklar** [microsoft/CsWinRT#699] opened 2021-01-27 21:42 UTC
Related to #693, #697, #698

- Created a C# NET 5 class library. Reference the WinUI 3 Preview 4 CI 1/26 nuget package.
- Follow the authoring instructions to produce a nuget pkg for the class library
- Created a cppwinrt WinUI 3 app from WinUI 3 Preview 3 VSIX
- update cppwinrt app's WinUI reference to latest internal WinUI nuget preview 4 from 01/26
- Referenced the NET 5 class library nupkg file from the cppwinrt app via a local nuget source
- Build solution

If I add a User Control in the NET 5 class library then when I try to use it from the C++/WinRT app I get this error:
> 1>cppwinrt : error 'Windows.Foundation.Metadata.GuidAttribute' attribute for type 'System.CodeDom.Compiler.GeneratedCodeAttribute' not found

**Comment by manodasanW** [comment] 2021-01-29 08:11
Confirmed dupe of #695

**Closed by manodasanW** 2021-01-29 08:11 UTC
Labels: bug
