### ISSUE TITLE
Can't assign a C# type derived from a projected type to a projected type's property

### ISSUE THREAD

**Issue by llongley** [microsoft/CsWinRT#276] opened 2020-05-13 23:49 UTC
See [this repro app](https://github.com/microsoft/CsWinRT/files/4625242/CsWinRtProjectionTest.zip) for an example.  If we assign an instance of the projected type VirtualizingLayout to the Layout property on ItemsRepeater, everything is fine.  However, if we assign an instance of a type derived from VirtualizingLayout that otherwise changes nothing, we crash when we call `pInstance->GetRuntimeClassName(&hRuntimeClassName)`.

**Comment by AdamBraden** [comment] 2020-10-09 17:11
@llongley - believe this is fixed in latest changes.

**Closed by AdamBraden** 2020-10-09 17:11 UTC
Labels: bug

**Comment by Scottj1s** [comment] 2020-10-09 17:13
most likely a dupe of #347
