### ISSUE TITLE
An assembly with the same simple name 'WinRT.Runtime' has already been imported

### ISSUE THREAD

**Issue by DethRaid** [microsoft/CsWinRT#424] opened 2020-09-22 17:27 UTC
I'm trying to use C#/WinRT in my .NET 5 project

I'm using .NET 5 RC1, Visual Studio 16.8 preview 3, and C#/WinRT 0.1.0-prerelease.200629.3

In .NET 5, the way I target WinRT with my application has changed. The recommended way (I can't find the blog post for it, sorry) is to set the `TargetFramework` in your `.csproj` to `net5.0-windows10.0.19041.0` (or another Windows version, but that's the one I'm targeting). When I do that and compile my project, I get the error from the title of this issue

My reading of the error is that both the WinRT framework and C#/WinRT are adding a reference to `Windows.Runtime`. I tried changing my `TargetFramework` to `net5.0`. When that happens I get a different error: "The type or namespace name 'Metadata' does not exist in the namespace 'Windows.Foundation'". It seems like now nothing is adding a reference to `Windows.Runtime`?

My C# project is [here](https://github.com/DethRaid/SanityEngine/tree/winrt/SanityEngine.NET)

**Comment by DethRaid** [comment] 2020-09-22 17:49
Here's the complete build output:
```
Rebuild started...
1>------ Rebuild All started: Project: Sanity.Engine.NET, Configuration: Debug Any CPU ------
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>E:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2121,5): warning MSB3243: No way to resolve conflict between "WinRT.Runtime, Version=0.1.0.2813, Culture=neutral, PublicKeyToken=null" and "WinRT.Runtime, Version=0.1.0.2153, Culture=neutral, PublicKeyToken=null". Choosing "WinRT.Runtime, Version=0.1.0.2813, Culture=neutral, PublicKeyToken=null" arbitrarily.
1>CSC : error CS1704: An assembly with the same simple name 'WinRT.Runtime' has already been imported. Try removing one of the references (e.g. 'C:\Users\gold1\.nuget\packages\microsoft.windows.sdk.net.ref\10.0.19041.3-preview\lib\WinRT.Runtime.dll') or sign them to enable side-by-side.
1>Done building project "Sanity.Engine.NET.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

**Comment by AdamBraden** [comment] 2020-09-22 20:12
Dupe of #7?  Try removing "WinRT" from your namespace/classname.

**Comment by manodasanW** [comment] 2020-09-22 20:17
I don't believe that is the same issue it as this isn't an activation issue, but rather a build time issue.  This is most likely due to WinRT.Runtime conflict issue due to file name casing that I addressed a week or so ago, working on confirming,

**Comment by FreddyD-GH** [comment] 2020-09-23 22:31
I encountered this same issue.  For me, I was able to workaround the issue by removing all explicit and implicit package references to CsWinRT after changing my TargetFramework to 'net5.0-windows10.0.19041.0'.  However, I was only using the projections in Microsoft.Windows.SDK.NET, not generating any of my own, so I'm not sure if that workaround is viable for this issue's author.

For what it's worth, the repro is extremely simple:
1. CLI: `dotnet new console -n TestApp -f net5.0`
2. Manually edit .csproj file to use TargetFramework of 'net5.0-windows10.0.19041.0' (I assume at some point `dotnet new console -n TestApp -f net5.0-windows10.0.19041.0` will work?)
3. CLI: `dotnet add package Microsoft.Windows.CsWinRT --version 0.1.0-prerelease.200629.3`
4. CLI: `dotnet build`

**Comment by DethRaid** [comment] 2020-09-23 22:33
I don't think your workaround will work for me, since I'm generating C# language projections at build time

**Comment by Scottj1s** [comment] 2020-09-24 00:07
The latest unlisted version of the Microsoft.Windows.CsWinRT nuget package (200923.3) may address this.  Please let us know if that doesn't help.

**Comment by DethRaid** [comment] 2020-09-24 02:16
I updated to that version of the CsWinRT package by changing the version number in my csproj file, and now I have different errors. Progress?

```
warning MSB3243: No way to resolve conflict between "WinRT.Runtime, Version=0.1.0.3023, Culture=neutral, PublicKeyToken=99ea127f02d97709" and "WinRT.Runtime, Version=0.1.0.2813, Culture=neutral, PublicKeyToken=null". Choosing "WinRT.Runtime, Version=0.1.0.3023, Culture=neutral, PublicKeyToken=99ea127f02d97709" arbitrarily.

CSC : warning CS8032: An instance of analyzer Generator.SourceGenerator cannot be created from C:\Users\gold1\.nuget\packages\microsoft.windows.cswinrt\0.1.0-prerelease.200923.3\analyzers\dotnet\cs\WinRT.SourceGenerator.dll : Method 'Initialize' in type 'Generator.SourceGenerator' from assembly 'WinRT.SourceGenerator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation..

1>E:\Documents\SanityEngine\SanityEngine.NET\Generated Files\Sanity.cs(20,20,20,38): error CS0433: The type 'WindowsRuntimeTypeAttribute' exists in both 'WinRT.Runtime, Version=0.1.0.2813, Culture=neutral, PublicKeyToken=null' and 'WinRT.Runtime, Version=0.1.0.3023, Culture=neutral, PublicKeyToken=99ea127f02d97709'
```

I have a lot more errors like the last one, where a type is defined in two assemblies and VS isn't sure how to resolve them

I cleaned and rebuild my project but got the same errors

I've updated the code in [the WinRT branch of my repo](https://github.com/DethRaid/SanityEngine/blob/winrt/SanityEngine.NET/Sanity.Engine.NET.csproj) with the new CsWinRT NuGet package

**Closed** 2020-09-24 12:19 UTC
Labels: bug

**Comment by DethRaid** [comment] 2020-09-24 14:38
I guess I'll make a new issue for my new errors
