### ISSUE TITLE
TypeInitializationException in PointCollection regression in (Windows App SDK) 0.8.2

### ISSUE THREAD

**Issue by Marv51** [microsoft/CsWinRT#967] opened 2021-08-18 12:19 UTC
Is https://github.com/microsoft/microsoft-ui-xaml/issues/5692 on your radar? It seems like a pretty clear regression in 1.3.3.

**Comment by Scottj1s** [comment] 2021-08-20 00:44
transferred issue 5692 above, so closing this as a dupe of #971

**Closed by Scottj1s** 2021-08-20 00:44 UTC
Labels: bug
