### ISSUE TITLE
Updating a projection package version requires 2 rebuilds

### ISSUE THREAD

**Issue by asklar** [microsoft/CsWinRT#821] opened 2021-04-24 08:45 UTC
App uses CsWinRT 1.2.5
App references a projection nuget version=0.1.0-prerelease. Make the nuget package reference an older CsWinRT like 1.0.0, this only matters so that we get a warning about mismatched versions (picking 1.2.5), and the warning prints out the version of the nupkg it picked.

Build the app
Generate a new projection nupkg, version=0.1.1-prerelease
Change the app to point to the 0.1.1-prerelease package
Build the app -> notice that it picks up the 0.1.0-prerelease according to the mismatch warning 
Build the app again, now it picks up 0.1.1-prerelease

**Comment by Scottj1s** [comment] 2021-04-26 15:48
This sounds more like a nuget restore issue.  Are you planning to distribute your projection nuget separately from the app?  If not, you can simplify by just having the app generate and compile cswinrt projection sources directly.

**Comment by asklar** [comment] 2021-04-26 15:50
yeah I think we will want to distribute the projection separately at some point, it's just a bit cumbersome to test things out

**Comment by angelazhangmsft** [comment] 2021-04-27 16:18
This doesn't seem like a CsWinRT issue - looks like a VS issue with nuget restore or not using the NuGet package manager UI to upgrade the version

**Comment by j0shuams** [comment] 2021-04-27 16:20
Things to try @asklar 
- after changing to 0.1.1; right click the solution in Solution Explorer and select "Restore Nuget Packages For Solution
- instead of manually editing the package reference, right click the project in Solution Explorer and select "Manage nuget packages" to update to 0.1.1 using the UI

**Comment by asklar** [comment] 2021-04-27 16:22
Using the manage packages UI seems to work, though that's a bunch more clicks

**Comment by zkat** [comment] 2021-05-04 17:36
@asklar if you can still repro this, do you mind filing an issue with more detailed repro steps, and possibly a repository that can reproduce this, over at https://github.com/nuget/home/issues/new?

**Comment by angelazhangmsft** [comment] 2021-05-18 18:20
Closing as this is not a CsWinRT issue

**Closed by angelazhangmsft** 2021-05-18 18:20 UTC
Labels: bug
