### ISSUE TITLE
Type with "WinRT" in its full name fails to activate

### ISSUE THREAD

**Issue by llongley** [microsoft/CsWinRT#401] opened 2020-09-03 19:28 UTC
There's this bit in the generated WinRT.cs file:

```
        public BaseActivationFactory(string typeNamespace, string typeFullName)
        {
            var runtimeClassId = typeFullName.Replace("WinRT", "Windows");

            // Prefer the RoGetActivationFactory HRESULT failure over the LoadLibrary/etc. failure
            int hr;
            (_IActivationFactory, hr) = WinrtModule.GetActivationFactory(runtimeClassId);
```

I'm assuming that this is handling something to do with system types, but the problem is that types can also just have this string in them legitimately, which this doesn't account for.  An example of this is the test authoring platform [TAEF](https://docs.microsoft.com/en-us/windows-hardware/drivers/taef/getting-started), which has the type `Microsoft.VisualStudio.TestPlatform.TestExecutor.WinRTCore.UnitTestClient` - this code changes that to `Microsoft.VisualStudio.TestPlatform.TestExecutor.WindowsCore.UnitTestClient`, which doesn't exist and as a result fails to activate.

I've implemented this as a workaround, injected by an MSBuild target that goes between C#/WinRT projection and C# compilation, which seems to work:

```
            (_IActivationFactory, hr) = WinrtModule.GetActivationFactory(runtimeClassId);
            if (_IActivationFactory == null) { (_IActivationFactory, hr) = WinrtModule.GetActivationFactory(typeFullName); }
```

**Comment by manodasanW** [comment] 2020-09-04 04:07
Dupe of #7

**Closed** 2020-09-04 21:40 UTC
