### ISSUE TITLE
Version 1.2.2 or greater produces "Path '7.0' is not a file or directory" error

### ISSUE THREAD

**Issue by alwilton** [microsoft/CsWinRT#822] opened 2021-04-25 22:00 UTC
Version 1.2.2 or greater produces "Path '7.0' is not a file or directory" error when building project

Reverting to version 1.2.1 or less removes this error

a secondary error also occurs:
MSB3073	The command ""C:\Users\Al\.nuget\packages\microsoft.windows.cswinrt\1.2.2\cswinrt.exe" @"C:\Users\Al\source\Workspaces\CMS\FSCMS\FsCms\obj\Debug\net5.0-windows\Generated Files\cswinrt.rsp"" exited with code 1

In fact, running that command from a command prompt does produce the error of "Path '7.0' is not a file or directory"

I am running VS 16.9.4 with .NET 5.0.202. This is a Winforms 5.0 application

**Comment by angelazhangmsft** [comment] 2021-04-27 15:45
@alwilton Do you have a repro you could share? I am not seeing this issue with Version 1.2.2. Are you generating a projection assembly? If so, you should use a C# class library project like in this [sample].(https://github.com/microsoft/CsWinRT/tree/master/src/Samples/Net5ProjectionSample)

**Comment by alwilton** [comment] 2021-04-27 16:02
I just created and uploaded a small project that creates the error on my system
[https://github.com/alwilton/WinRtTest](https://github.com/alwilton/WinRtTest)

**Comment by angelazhangmsft** [comment] 2021-04-27 22:24
@alwilton - I took a look at your project, you can set the following property to workaround that error:
```xml
<CsWinRTEnabled>false</CsWinRTEnabled>
```
Curious, what are you using the cswinrt package for? I see this is an application project.

**Comment by alwilton** [comment] 2021-04-27 22:43
The ‘real’ much larger application that I am using it for requires it. Without the package I get the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1130	Referencing a Windows Metadata component directly when targeting .NETCoreApp,Version=v5.0 is not supported. Use the C#/WinRT projection tool (https://aka.ms/cswinrt) or a provided projection for this target.	PCMS	C:\Program Files\dotnet\sdk\5.0.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets	983	

I tried adding the <CsWinRTEnabled>false</CsWinRTEnabled> to the property group as follows without success

```
    <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <CsWinRTEnabled>false</CsWinRTEnabled>
  </PropertyGroup>

```

**Comment by alwilton** [comment] 2021-04-27 23:56
I just triedremoveing the CsWinRt package from the provided sample project and got the above NETSDK1130 error as well

**Comment by angelazhangmsft** [comment] 2021-04-28 00:29
@alwilton I see, this error message is misleading as it seems like you have a reference to a component that doesn't target .NET 5. We have added a better error message to explicitly list which component is causing the error which will be in a future version of VS. Hm, do you still get the secondary error involving cswinrt.exe when you set the `CsWinRTEnabled` property? It should disable cswinrt.exe from executing.

**Comment by alwilton** [comment] 2021-04-28 15:02
I added the following to the project and now it does compile successfully

```
  <PropertyGroup>
    <CsWinRTEnabled >false</CsWinRTEnabled>
  </PropertyGroup>

```

**Comment by angelazhangmsft** [comment] 2021-04-28 16:02
@alwilton Great, closing and marking this issue as resolved.

**Closed by angelazhangmsft** 2021-04-28 16:02 UTC
Labels: bug

**Comment by angelazhangmsft** [comment] 2021-04-29 00:51
From investigation it seems this change is the reason for the "Path 7.0" error instead of the NETSDK1130 error: #786

**Comment by smaillet** [comment] 2021-08-24 16:35
How is this resolved? It still doesn't work. and we still get the same "error : Path '7.0' is not a file or directory" with no workaround. (The one provided above is NOT by any means a workaround, since completely disables the functionality of the package - might as well not even reference the CsWinRT package if that is on - it's useless to do that) I have a library that is targeting NET5.0 and needs to use a WinRT API, which is no longer built into the RT/compiler so I'm now supposed to use this C#/WinRT package - but it doesn't work, so I'm stuck without any options...

**Comment by angelazhangmsft** [comment] 2021-08-25 00:08
Hi @smaillet, in order to use a WinRT API with .NET 5, you can edit the `TargetFramework` property in your project, for example:

```xml
<TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
```
These docs have more details on calling WinRT APIs in a desktop app: https://docs.microsoft.com/windows/apps/desktop/modernize/desktop-to-uwp-enhance

The CsWinRT NuGet package should only be used for generating C# projections from a winmd component, or for generating a winmd component.

**Comment by edwardskrod** [comment] 2022-04-08 22:24
I wonder why this didn't work:
    <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <CsWinRTEnabled>false</CsWinRTEnabled>
  </PropertyGroup>

But this did:

  <PropertyGroup>
    <CsWinRTEnabled >false</CsWinRTEnabled>
  </PropertyGroup>


I'm also running into this issue.

**Comment by edwardskrod** [comment] 2022-04-08 22:26
> @alwilton I see, this error message is misleading as it seems you have a reference to a component that doesn't target .NET 5. We are working on a better error message to explicitly list which component is causing the error, which will be in a future version of VS.
> 
> Hm, do you still get the secondary error involving cswinrt.exe when you set the `CsWinRTEnabled` property? It should disable cswinrt.exe from executing.

@angelazhangmsft Did we ever prioritize a better error message?  I just ran into the same issue on 17.3.

**Comment by angelazhangmsft** [comment] 2022-04-08 23:18
@edwardskrod are you setting the TFM to a Windows specific version, e.g. net6.0-windows10.0.19041.0? The reason for the error is that `CsWinRTWindowsMetadata` defaults to the `TargetPlatformVersion` and uses the SDK for that version.

**Comment by cosmin42** [comment] 2023-08-26 19:36
This issue is till there, in my case CsWinRTEnabled needs to be true because I'm trying to use CSWinRT to project a WinRT/C++ component.
The minimum sample solution that reproduces the problem: https://github.com/cosmin42/Sample
