### ISSUE TITLE
[.NET | Self-contained] Allow CsWinRT component to work as .NET self-contained when packaged with a C++ App.

### ISSUE THREAD

**Issue by RobsonPontin** [microsoft/CsWinRT#1524] opened 2024-03-05 17:58 UTC
Hello,

## Summary
In an architecture where we have a WinUI 3 C++ application and a CsWinRT component dependency, we would like to have a simple way to deploy it as .NET self-contained, so customers won't need to install .NET runtime locally.

## Rationale
Since a C++ App (WinUI 3 in this case) does not support publish profiles, we need to use an extra component using a [custom .NET runtime host](https://learn.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting) tech to overwrite the behavior to WinRT-Host to then load .NET dlls from the installed packaged app location instead of OS installed location.

The idea is for the CsWinRT component (or WinRT host) to do this job.

## Important Notes
Here is a sample project for your reference of a similar architecture where I'm packaging the application using [DNNE](https://github.com/AaronRobinsonMSFT/DNNE) to make it .NET self-contained.

https://github.com/RobsonPontin/WinUI3/tree/main/DotNetSelfContainedNativeApp

![image](https://github.com/microsoft/CsWinRT/assets/6156513/c1d1f0e3-c20a-4881-8c63-909999051d47)

## Open Questions
1. Could this be done with a PublishProfile which the CsWinRT component could use during Native App packaging/deployment?

**Comment by manodasanW** [comment] 2024-03-05 21:33
Dupe of #1141

**Closed by manodasanW** 2024-03-05 21:33 UTC
Labels: enhancement
