### ISSUE TITLE
Impossible to use a net5.0-windows10.... TFW library assembly from a net5.0 TFW application assembly

### ISSUE THREAD

**Issue by YvesDolce** [microsoft/CsWinRT#1170] opened 2022-04-13 00:56 UTC
**Describe the bug**
I think the the title is clear

**To Reproduce**
Create two such projects, the .NET 5.0 one referring to the library where the TFW is net5.0-windows10..., you'll see the error.

`error NU1201: Project Executable is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Project Library supports: net6.0-windows10.0.19041 (.NETCoreApp,Version=v6.0)`

**Expected behavior**
That it works

**Version Info**
VS2022, .NET 5.0 or .NET 6.0

**Additional context**
To be honest, I'm not sure if this is a bug or rather just by design but I haven't been able to find any information about  that scenario.

**Comment by angelazhangmsft** [comment] 2022-04-13 15:53
@YvesDolce, can you confirm what the `TargetFramework` for the library project and the app project? 

If the library is targeting `net6.0-windows10.0.19041.0`, the app will also need to target `net6.0-windows10.0.19041.0` or later.

**Comment by YvesDolce** [comment] 2022-04-13 19:24
Thanks @angelazhangmsft. The app is `<TargetFrameworks>net6.0</TargetFrameworks>` and the library is `net6.0-windows10.0.19041.0`. From your answer, I understand it's by design. Do you know the reason? I understand that the application could be launched on Linux/iOS and that that Windows specific library (DLL) would prevent its successfull loading/execution but is that the reason?

Is there a workaround? Would **Embedded support for WinRT types** be a way to solve this then?

**Comment by angelazhangmsft** [comment] 2022-04-14 00:29
@YvesDolce yes that's by design - you could multi-target and add platform guards around OS-specific calls as described in these docs: https://docs.microsoft.com/dotnet/standard/frameworks#net-5-os-specific-tfms

Embedded support is also an option, if the WinRT types you are using are all internal and don't need to be publicly exposed. I believe you can target `net6.0` in your library and use embedded support (cc @j0shuams).

**Comment by angelazhangmsft** [comment] 2022-04-21 00:24
Closing this issue as by design.

**Closed by angelazhangmsft** 2022-04-21 00:24 UTC
Labels: bug
