### ISSUE TITLE
Error name with UWP Modern .NET templates

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/CsWinRT#1788] opened 2024-09-12 01:46 UTC
**Describe the bug**

Error name with UWP Modern .NET templates

**To Reproduce**

![{08AFA661-74DD-46B2-B856-B325A0018C2D}](https://github.com/user-attachments/assets/8f190f9e-98db-446f-85c4-dc49833a7fcf)

**Expected behavior**

Simple name

**Version Info**

.NET 9

**Additional context**

None

**Comment by Sergio0694** [comment] 2024-09-12 17:49
Closing this as it's a duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/9977. I'll fix it in a future update 🙂

**Closed by Sergio0694** 2024-09-12 17:49 UTC
Labels: bug, external
