### ISSUE TITLE
No common prefix namespace issues with internal classes

### ISSUE THREAD

**Issue by andrewleader** [microsoft/CsWinRT#721] opened 2021-02-05 02:56 UTC
**Describe the bug**
I'm getting compile-time errors because of **internal** classes that use sub-namespaces. Our root namespace and project/file name is `Microsoft.Toolkit.Uwp.Notifications`, but for some internal classes I use the namespace `Microsoft.Toolkit.Uwp.Notifications.Adaptive`... the only classes produced out of there are internal classes though.

**To Reproduce**

1. Create a new project named Microsoft.Toolkit.Uwp.Notifications
2. Include this code
```csharp
namespace Microsoft.Toolkit.Uwp.Notifications.Adaptive
{
    internal static class AdaptiveHelper
```

**Expected behavior**
I'd expect that internal classes don't generate public namespaces thus I should be able to use whatever namespaces I want internally

**Version Info**

CsWinRT NuGet 1.1.1
net5.0-windows10.0.19041

**Additional context**

**Comment by manodasanW** [comment] 2021-02-05 03:30
I assume you are trying to author a WinRT component in C#.  If so, this is a dupe of #705 .

**Closed by manodasanW** 2021-02-05 03:30 UTC
Labels: bug
