### ISSUE TITLE
Question: How can I implement a WinRT interface with .NET 5?

### ISSUE THREAD

**Issue by smourier** [microsoft/CsWinRT#799] opened 2021-04-13 06:23 UTC
### Description

What I'm just trying to do is implement with C# / .NET 5 a WinRT interface.
This is the same issue as explained here: https://github.com/dotnet/runtime/issues/46264

Here is a C# console app, using C#/WinRT projection.

	<Project Sdk="Microsoft.NET.Sdk">

	  <PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
	  </PropertyGroup>

	</Project>

Program.cs:
	
	using System;
	using System.Runtime.InteropServices;
	using Windows.Data.Xml.Dom;

	namespace ConsoleApp1
	{
		class Program
		{
			static void Main()
			{
				var n = new Node();
				Node(n);
			}

			// calling a native Dll using interop
			[DllImport(@"..\..\..\..\x64\Debug\Dll1.dll")]
			private static extern int Node([MarshalAs(UnmanagedType.IUnknown)] object punk);
		}

		// I used IXmlNodeSelector as an example, other WinRT interfaces create the same issue.
		public class Node : IXmlNodeSelector
		{
			// we won't even get to the throws
			public XmlNodeList SelectNodes(string xpath) => throw new NotImplementedException();
			public IXmlNode SelectSingleNodeNS(string xpath, object namespaces) => throw new NotImplementedException();
			public XmlNodeList SelectNodesNS(string xpath, object namespaces) => throw new NotImplementedException();
			public IXmlNode SelectSingleNode(string xpath) => throw new NotImplementedException();
		}
	}

In my C++ native "Dll1.dll" , I just have this code:
	
	extern "C" __declspec(dllexport) HRESULT __stdcall Node(IUnknown * unk)
	{
		IXmlNodeSelector* selector; // from ABI::Windows::Data::Xml::Dom
		HRESULT hr = unk->QueryInterface(IID_PPV_ARGS(&selector));
		if (SUCCEEDED(hr))
		{
			// This is where the crash happens
			hr = selector->SelectSingleNode(NULL, NULL);
			selector->Release();
		}
		return S_OK;
	}

This is what I see on the console when SelectSingleNode is called.

```
Fatal error. Internal CLR error. (0x80131506)
Repeat 2 times:
--------------------------------
   at ConsoleApp25.Program.<Main>g__Node|0_0(System.Object)
--------------------------------
   at ConsoleApp25.Program.Main()
```

### Configuration

.NET 5.0.4, Windows 10 20H2 19042.906 64bits. Visual Studio 2019 16.9.3.

### Regression?

All this works fine with .NET Framework (and I think it also worked with .NET Core 3.1) with the "old" *Microsoft.Windows.SDK.Contracts* nuget.

### Other information

This is what I see in WinDBG, I think for some reason the wrapper is called on some IDispatch implementation (where is this IDispatch coming from?) and crashes on IID comparison (of course). 

![winrtcomcore](https://user-images.githubusercontent.com/5328574/102710888-f3b26280-42b5-11eb-8cb4-539910e622b1.png)

There's a reproducing project and solution, just build it in X64 and run.
[WinRTComCore.zip](https://github.com/dotnet/runtime/files/5720782/WinRTComCore.zip)

**Comment by angelazhangmsft** [comment] 2021-04-13 17:41
@smourier if I understand correctly, you can use C++/WinRT to build a winmd for your native component, and then use C#/WinRT to build the interop layer. Here's a sample of building a projection: https://github.com/microsoft/CsWinRT/tree/master/src/Samples/Net5ProjectionSample

**Comment by smourier** [comment] 2021-04-13 17:52
Thanks for your answer.

Maybe I'm wrong but I'm not sure I see the relation.

I don't have any "component", I don't want to package anything or create a WinMD, I just want to implement a WinRT *existing* interface (like IXmlNodeSelector)  using C#. This "just worked" before CsWinRT.

**Comment by Scottj1s** [comment] 2021-04-13 19:37
Hi @smourier, the call to SelectSingleNode is expecting storage for the output, something like:
IXmlNode* nodePtr;
SelectSingleNode( "somenode", &nodePtr);
Can you start with a known working sample and try to port that over to C#/WinRT?

**Comment by AaronRobinsonMSFT** [comment] 2021-04-13 20:00
@Scottj1s The actual call to `SelectSingleNode` isn't the problem, it is the runtime marshalling. In this scenario the implicit marshal call in `private static extern int Node([MarshalAs(UnmanagedType.IUnknown)] object punk);` is the issue. The system looks at the type and computes the implemented interface as [`ComInterfaceType.InterfaceIsDual`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.cominterfacetype). This means it takes the 4 declared functions on `IXmlNodeSelector` and appends them to an `IDispatch` vtable. The problem is the `IXmlNodeSelector` interface is actually `IInspectable` not `IDispatch` but the runtime doesn't know that because all understanding of the `IInspectable` layout was removed.

The solution to the scenario is to avoid using the type with the built-in system and instead implement the type in C# - which seems to be possible [here](https://github.com/microsoft/CsWinRT/blob/master/docs/authoring.md). The secondary issue involving interactions with the built-in system are the next concern because at present it is a hard crash for a myriad of reasons I explained in https://github.com/dotnet/runtime/issues/46264#issuecomment-818438366.

**Comment by smourier** [comment] 2021-04-13 20:24
Hi @Scottj1s, I believe that's exactly what I gave.

The problem is a crash ("Internal CLR error") due to a wrong vtable, not some "invalid argument" expected error, as @AaronRobinsonMSFT explained. I just picked this interface, but the problem is with all IInspectable WinRT interfaces.

Wouldn't that be possible to decorate the generated C# IInspectable interfaces with ComInterfaceType.InterfaceIsIInspectable? Otherwise, what's the point of this enum value with .NET Core?

**Comment by AaronRobinsonMSFT** [comment] 2021-04-13 20:36
> Otherwise, what's the point of this enum value with .NET Core?

@smourier Unfortunately it is now a legacy value that we can't remove for other reasons. However, the point about it being reusable in this scenario is appropriate I believe &ndash; barring it isn't catastrophic to C#/WinRT in some other non-obvious way.

**Comment by Scottj1s** [comment] 2021-04-13 20:36
I was going off the description:
  hr = selector->SelectSingleNode(NULL, NULL);

Another option is to create an interop interface in IDL, and project that via C#/WinRT, versus hand-rolling a DLL export and marshaling as IUnknown.  Unfortunately, support for ComInterfaceType.InterfaceIsIInspectable has been removed from the CLR.

**Comment by AaronRobinsonMSFT** [comment] 2021-04-13 20:39
>Unfortunately, support for ComInterfaceType.InterfaceIsIInspectable has been removed from the CLR.

Yep. That is the idea. If the types are marked as such the above scenario wouldn't crash since an error HRESULT would be returned from `QueryInterface()` instead of `S_OK`.

**Comment by Scottj1s** [comment] 2021-04-13 20:50
I see, so for the side effect of avoiding the IDispatch layout generation?

**Comment by smourier** [comment] 2021-04-14 05:45
This would at least fix the vtable mixup/crash, which I must say as a 25-years old COM developer is intolerable :-)

But, back to my original question, the possibility to simply implement a WinRT/IInspectable interface in C#?

I understand IInspectable implementation support has gone from .NET itself (which makes me sad but ok), so, could it be possible to add something to C#/WinRT? possibly optional? Maybe something like this:

	public class Node : WinRT.SomeRuntimeThing<IXmlNodeSelector> // in the runtime?
	{
		...
	}
	
or

	public class Node : IXmlNodeSelectorWinRTGenerated // some generated class/interface/struct?
	{
		...
	}

**Comment by AaronRobinsonMSFT** [comment] 2021-04-14 15:40
>But, back to my original question, the possibility to simply implement a WinRT/IInspectable interface in C#?

@smourier Like the removed built-in support for `IInspectable`, the C#/WinRT tooling provides an implementation of `IInspectable` but the tooling must be run to generate it. One of our goals was to stop run time generation of interop code for WinRT and move it to compile time. There are many benefits to this but one of the biggest drawbacks is the previous simplicity of implementing part of an interface (that is, the non-`IUnknown`, non-`IInspectable` parts) and letting the .NET runtime generate that for you on the fly no longer works. Unfortunately in this case it is really poor.

I've personally not tried this but support is in Preview to have the tooling generate the `IInspectable` code for you. @angelazhangmsft pointed out those instructions [here](https://github.com/microsoft/CsWinRT/blob/master/docs/authoring.md#authoring-a-cwinrt-component). Once the C#/WinRT tooling has done its job, the next step would be to pass it to a P/Invoke. This will be slightly different now because the runtime is no longer involved. Let's take the P/Invoke from the example: `private static extern int Node([MarshalAs(UnmanagedType.IUnknown)] object punk);`. Marking the argument as `MarshalAs(UnmanagedType.IUnknown)` tells the runtime it should use the built-in system, but what is needed is to use what C#/WinRT has done. At the moment the best way to do this would be to update the signature to: 

```csharp
private static extern int Node(IntPtr punk);
```

In order to get at the `IntPtr` that represents the `Node` instance is possible through types in the WinRT.Runtime.dll assembly, or likely on the generated code for `Node`, I would have to defer to one of the C#/WinRT experts &ndash; @Scottj1s or @manodasanW?

From a UX perspective this is much poorer than before because all of the previous hidden parts are now in your face and I agree it is more complicated. Here is why we think this current state, which can be improved, is better than before.

1) The P/Invoke in question can now be inlined and will execute faster because all code was computed at run time. This example doesn't showcase that win.
1) Since all the code is pre-generated the application is now AOT friendly that becomes important as .NET continues to evolve and WinRT is primed to step into that world.
1) The evolution and expansion of WinRT can now be driven by the WinRT ecosystem owners. The .NET team didn't have the resources to maintain and evolve that system so types line `Span<T>` and nullable types were previously supported. The WinRT can now innovate and respond to user feedback.
1) Stability is now possible. The previous system had to remain static because it was a part of the runtime. This meant if we fixed a bug that users had come to rely upon &ndash; this happens all the time &ndash; they would be broken in the next version. There was no way to update the runtime without getting the new interop. C#/WinRT enables this stability option.

An opportunity to make this better would be for the C#/WinRT team to provide a specialized `ICustomMarshaler` instance that could be used to mark existing P/Invokes and hide some of the work:

```csharp
private static extern int Node([MarshalAs(UnmanagedType.CustomMarshaler,
             MarshalType="WinRT.InterfaceMarshaler")] object csWinRTType);
```

**Comment by Scottj1s** [comment] 2021-04-15 16:13
Yes to Aaron's suggestion to change the signature of the interop function, Node.  As the problem is with the marshaling logic in the CLR itself (getting confused with IDispatch), the interface should be passed as a raw IntPtr to avoid that.  This can be done via the C#/WinRT [FromManaged](https://github.com/microsoft/CsWinRT/blob/master/docs/interop.md#Create-CCW) functions to create a CCW for your interop scenario.  On the inside of Node, you would then need to cast that incoming void* to an appropriate smart pointer, via something like [winrt::attach-abi](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/attach-abi)

**Comment by smourier** [comment] 2021-04-15 16:52
If I understand correctly, you're saying that I must replace this:

        static void Main()
        {
            var n = new Node();
            Node(n);
        }

        // calling a native Dll using interop
        [DllImport(@"..\..\..\..\x64\Debug\Dll1.dll")]
        private static extern int Node([MarshalAs(UnmanagedType.IUnknown)] object punk);

by this:

        static void Main()
        {
            var n = new Node();
            var ptr = MarshalInterface<IXmlNodeSelector>.FromManaged(n);
            Node(ptr);
        }

        [DllImport(@"..\..\..\..\x64\Debug\Dll1.dll")]
        private static extern int Node(IntPtr punk);

And I will get the IInspectable implemented for me (by C#/WinRT)?

**Comment by Scottj1s** [comment] 2021-04-15 17:06
Yes - can we try that?

**Comment by smourier** [comment] 2021-04-15 17:16
Oh, I thought it was working as of today :-)

Anyway, yes, that would be great. I'm a bit sad that the C# interop code is not compatible from .NET to .NET 5+ (it needs quite a rework), but that's a working solution, and that's what's important 👍

**Comment by Scottj1s** [comment] 2021-04-15 19:01
agreed - the gap is unfortunate, and you are certainly right to insist on robust and actionable failure

**Comment by angelazhangmsft** [comment] 2021-10-29 19:39
Closing as there is a workaround, and marking all our interfaces with another attribute to prevent .NET from projecting IDispatch is a lot of overhead for this edge case scenario.

**Closed by angelazhangmsft** 2021-10-29 19:39 UTC
Labels: enhancement, question
