### ISSUE TITLE
Windows.Storage.Pickers.FileSavePicker.FileTypeChoices.Add throw System.InvalidCastException: 'Specified cast is not valid.' with PublishAOT=true

### ISSUE THREAD

**Issue by optsing** [microsoft/CsWinRT#1797] opened 2024-09-24 12:51 UTC
**Describe the bug**
Windows.Storage.Pickers.FileSavePicker.FileTypeChoices.Add throw System.InvalidCastException: 'Specified cast is not valid.' with PublishAOT=true
With PublishAOT=false everything works fine.

1. Create new WinAppSDK project
2. Add  `<WindowsSdkPackageVersion>10.0.22621.45</WindowsSdkPackageVersion>` and `<PublishAot>true</PublishAot>` to csproj
3. Add to myButton_Click
```
var picker = new Windows.Storage.Pickers.FileSavePicker();
WinRT.Interop.InitializeWithWindow.Initialize(picker, WinRT.Interop.WindowNative.GetWindowHandle(this));
picker.FileTypeChoices.Add("Text file", [".txt"]);
picker.SuggestedStartLocation = Windows.Storage.Pickers.PickerLocationId.DocumentsLibrary;
var file = await picker.PickSaveFileAsync();
``` 

**Expected behavior**

After clicking on the button, the Save File dialog box should be displayed

**Version Info**
NET: 8.0.401
CsWinRT: 2.1.3
Microsoft.Windows.SDK.NET.Ref: 10.0.22621.45 or 10.0.26100.45

**Comment by Sergio0694** [comment] 2024-09-24 14:31
Possibly related to or duplicate of https://github.com/microsoft/CsWinRT/issues/1661?

**Comment by manodasanW** [comment] 2024-09-24 17:53
This does look to be a dupe.  In the add, a collection expression is being used.  Addressing that is being tracked by the above mentioned issue.  In the meant time for AOT, you would need to use an array or another collection.

**Comment by optsing** [comment] 2024-09-24 20:40
> This does look to be a dupe. In the add, a collection expression is being used. Addressing that is being tracked by the above mentioned issue. In the meant time for AOT, you would need to use an array or another collection.

I think it's too early to close this issue, because when using string[] or List<string> as an argument, the error is the same.

**Comment by manodasanW** [comment] 2024-09-25 00:16
@optsing Can you confirm whether or not you have a CsWinRT package reference on your project where you are doing this?  Until the upcoming .NET SDK servicing update, our source generator doesn't run standalone and needs to enabled by a property set in the CsWinRT package.

**Comment by optsing** [comment] 2024-09-25 01:14
> @optsing Can you confirm whether or not you have a CsWinRT package reference on your project where you are doing this? Until the upcoming .NET SDK servicing update, our source generator doesn't run standalone and needs to enabled by a property set in the CsWinRT package.

Oh, sorry, specified the version in Version Info, but forgot to mention adding the package in the steps to reproduce the bug.
Yes, the CSWinRT package version 2.1.3 has been added but the same result without it.

Examples of Exceptions:
![image](https://github.com/user-attachments/assets/98614a9a-d757-428c-b442-44550d2b9be6)
![image](https://github.com/user-attachments/assets/e310163f-adb5-4ac0-828b-f07aaa2f02e8)

**Comment by optsing** [comment] 2024-10-10 16:14
I noticed that FileSavePicker suddenly works in a complex project, but still doesn't work on minimal repro project with CSWinRT 2.1.5. Comparing the CSWinRT generated files, the WinRTGenericInstantiation.g.cs file is missing in the last case, and this is the problem.

**Comment by jevansaks** [comment] 2024-11-07 17:15
I hit this too. I was able to work around it by putting this in one of my public class's APIs:
```
        public List<string> Test => new();
```

Just to hint CsWinRT that it needs to generate the type info for List<string>, but obviously this is not ideal. :)

**Closed** 2024-11-11 00:54 UTC
Labels: bug, AOT
