### ISSUE TITLE
Crash in C++ app when trying to instantiate type from C# library

### ISSUE THREAD

**Issue by asklar** [microsoft/CsWinRT#700] opened 2021-01-27 21:43 UTC
Related to #693, #697, #698, #699

- Created a C# NET 5 class library. Reference the WinUI 3 Preview 4 CI 1/26 nuget package.
- Follow the authoring instructions to produce a nuget pkg for the class library
- Created a cppwinrt WinUI 3 app from WinUI 3 Preview 3 VSIX
- update cppwinrt app's WinUI reference to latest internal WinUI nuget preview 4 from 01/26
- Referenced the NET 5 class library nupkg file from the cppwinrt app via a local nuget source
- Build solution

After adding the winrt.host.runtimeconfig.json and the app1.exe.manifest to the WAP, the WAP project can start, however it crashes when instantiating a type from the library with "Error in DLL"

**Comment by manodasanW** [comment] 2021-01-27 21:46
Potential dupe of #696

**Closed** 2021-01-27 21:47 UTC
Labels: bug
