### ISSUE TITLE
Code generation bug from Windows.Foundation.UniversalApiContract.winmd

### ISSUE THREAD

**Issue by Silver-Fang** [microsoft/CsWinRT#841] opened 2021-05-11 13:28 UTC
**Describe the bug**
The code generated from "C:\Program Files (x86)\Windows Kits\10\References\10.0.19041.0\Windows.Foundation.UniversalApiContract\10.0.0.0\Windows.Foundation.UniversalApiContract.winmd" has critical bugs that block the compilation.

**To Reproduce**
1. Run
```Batch
.\cswinrt.exe -input "C:\Program Files (x86)\Windows Kits\10\References\10.0.19041.0\Windows.Networking.Connectivity.WwanContract\2.0.0.0\Windows.Networking.Connectivity.WwanContract.winmd" "C:\Program Files (x86)\Windows Kits\10\References\10.0.19041.0\Windows.Foundation.FoundationContract\4.0.0.0\Windows.Foundation.FoundationContract.winmd" "C:\Program Files (x86)\Windows Kits\10\References\10.0.19041.0\Windows.Foundation.UniversalApiContract\10.0.0.0\Windows.Foundation.UniversalApiContract.winmd" -output "C:\Users\vhtmf\Documents\CsWinRT"
```
in Windows Terminal
2. Create a .Net 5 library project with Visual Studio. Add code files and the CsWinRT NuGet package.
3. Compilation fails because of an error in Windows.UI.Xaml.Inputs.cs, line 4793 to 4803:
```C#
        public event global::System.EventHandler CanExecuteChanged
        {
            add => AsInternal(new InterfaceTag<ICommand>()).CanExecuteChanged += value;
            remove => AsInternal(new InterfaceTag<ICommand>()).CanExecuteChanged -= value;
        }

        event global::System.EventHandler ICommand.CanExecuteChanged
        {
            add => this.CanExecuteChanged += value;
            remove => this.CanExecuteChanged -= value;
        }
```
The type of the events, global::System.EventHandler, is wrong. It lacks the general argument <object>. Manually modify the code to:
```C#
        public event global::System.EventHandler<object> CanExecuteChanged
        {
            add => AsInternal(new InterfaceTag<ICommand>()).CanExecuteChanged += value;
            remove => AsInternal(new InterfaceTag<ICommand>()).CanExecuteChanged -= value;
        }

        event global::System.EventHandler<object> ICommand.CanExecuteChanged
        {
            add => this.CanExecuteChanged += value;
            remove => this.CanExecuteChanged -= value;
        }
```
Error solved. Compilation succeeded.

**Expected behavior**
The generated code should be absolutely correct.

**Version Info**
CsWinRT 1.2.5, .Net 5, Windows 10.0.19041

**Comment by asklar** [comment] 2021-05-13 17:48
Duplicate of #597

**Comment by Silver-Fang** [comment] 2021-05-13 22:41
> Duplicate of #597

Wow, still not fixed after half a year. Cool.

**Comment by angelazhangmsft** [comment] 2021-05-20 22:30
@Silver-Fang, can you expand on  your scenario? Are you trying to build your own Windows projection or use the Windows.UI.Xaml APIs?

**Comment by Silver-Fang** [comment] 2021-05-20 23:23
> @Silver-Fang, can you expand on your scenario? Are you trying to build your own Windows projection or use the Windows.UI.Xaml APIs?

I want to send windows toast notifications from a .Net 5 application. However, this function relies on UniversalApiContract, which does not support .Net 5 platform. I have to build it from source code.

**Comment by andrewleader** [comment] 2021-05-20 23:39
Hi @Silver-Fang, you can send Windows toast notifications from a .NET 5 app without having to build from source, **here is the documentation for sending a toast notification from a .NET app:** https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast?tabs=desktop

In short...

1. Make sure your .NET 5 TFM's app is set to `net5.0-windows10.0.17763.0` or higher (you need to reference `windows10.0.x.0` in order for the Windows 10 APIs to be included)
2. Install the [WCT Notifications NuGet package](https://www.nuget.org/packages/Microsoft.Toolkit.Uwp.Notifications/) in your app
3. Send a toast with the code below

```csharp
// Requires Microsoft.Toolkit.Uwp.Notifications NuGet package version 7.0 or greater
new ToastContentBuilder()
    .AddArgument("action", "viewConversation")
    .AddArgument("conversationId", 9813)
    .AddText("Andrew sent you a picture")
    .AddText("Check this out, The Enchantments in Washington!")
    .Show(); // Not seeing the Show() method? Make sure you have version 7.0, and if you're using .NET 5, your TFM must be net5.0-windows10.0.17763.0 or greater
```

**Comment by Silver-Fang** [comment] 2021-05-21 07:20
> Hi @Silver-Fang, you can send Windows toast notifications from a .NET 5 app without having to build from source, **here is the documentation for sending a toast notification from a .NET app:** https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast?tabs=desktop
> 
> In short...
> 
> 1. Make sure your .NET 5 TFM's app is set to `net5.0-windows10.0.17763.0` or higher (you need to reference `windows10.0.x.0` in order for the Windows 10 APIs to be included)
> 2. Install the [WCT Notifications NuGet package](https://www.nuget.org/packages/Microsoft.Toolkit.Uwp.Notifications/) in your app
> 3. Send a toast with the code below
> 
> ```cs
> // Requires Microsoft.Toolkit.Uwp.Notifications NuGet package version 7.0 or greater
> new ToastContentBuilder()
>     .AddArgument("action", "viewConversation")
>     .AddArgument("conversationId", 9813)
>     .AddText("Andrew sent you a picture")
>     .AddText("Check this out, The Enchantments in Washington!")
>     .Show(); // Not seeing the Show() method? Make sure you have version 7.0, and if you're using .NET 5, your TFM must be net5.0-windows10.0.17763.0 or greater
> ```

Wow, so tricky

**Comment by manodasanW** [comment] 2021-06-02 20:29
@Silver-Fang were you able to follow those steps and get your issue resolved?

**Comment by Silver-Fang** [comment] 2021-07-01 03:22
> @Silver-Fang were you able to follow those steps and get your issue resolved?

Yes

**Closed** 2021-07-01 03:45 UTC
Labels: bug
