### ISSUE TITLE
Add support for warnings when using APIs not compatible with min supported version

### ISSUE THREAD

**Issue by manodasanW** [microsoft/CsWinRT#293] opened 2020-06-01 02:36 UTC
Created based on #283 

> Will this nuget package also include warnings when using an api that you need to feature-check on older builds?

We should look at if we can achieve this using a Roslyn analyzer that takes a input of the supported Windows versions.

**Comment by hansmbakker** [comment] 2020-06-01 09:54
There is a [relevant analyzer in the community toolkit](https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/2999) but currently it is outdated and @michael-hawker [suggested that another place might be better for it](https://github.com/windows-toolkit/WindowsCommunityToolkit/pull/2999#issuecomment-635686542)

**Comment by michael-hawker** [comment] 2020-07-21 23:01
Thanks @hansmbakker for calling out the toolkit. This has been a big challenge for us, it was a great initial idea, but we soon realized the data isn't exposed to easily help a developer with analyzers based on their project settings. I think it's an unsupported scenario, which makes it difficult for us to provide value.

I don't know if this is something the CsWinRT folks can help with? If so great. It'd be great to just see this natively supported in VS as I think we can't go anywhere with our current analyzer?

**Comment by AdamBraden** [comment] 2020-10-09 17:25
related to #411

**Comment by stevenbrix** [comment] 2020-10-15 21:08
@manodasanW is this going to be different from #411? My understanding is that the .NET SDK will provide the analyzers if you are using the `SupportedOSPlatformVersion` property (equivalent to our `TargetPlatformMinVersion` property that exists today), along with those attributes.

See https://github.com/dotnet/designs/blob/main/accepted/2020/net5/net5.md#mapping-to-properties

**Comment by Scottj1s** [comment] 2020-11-06 01:07
looks like a dupe of #411

**Closed by Scottj1s** 2020-11-06 01:07 UTC
Labels: enhancement
