### ISSUE TITLE
Custom attributes are not processed by cswinrt

### ISSUE THREAD

**Issue by asklar** [microsoft/CsWinRT#946] opened 2021-07-31 06:08 UTC
```cs
    [global::System.AttributeUsage(global::System.AttributeTargets.All, Inherited = false, AllowMultiple = true)]
    sealed class MyAttribute : global::System.Attribute
    {
        readonly string positionalString;

        // This is a positional argument
        public MyAttribute(string positionalString)
        {
            this.positionalString = positionalString;
        }

        public string PositionalString
        {
            get { return positionalString; }
        }

        // This is a named argument
        public int NamedInt { get; set; }
    }

    [My("hello", 42)]
    public sealed class CustomButton : Button
    {
//... the rest
```

Expected: MyAttribute ends up in the winmd, and CustomButton has it
Actual: MyAttribute is ignored, does not end up in the metadata, and CustomButton doesn't have it.

**Comment by asklar** [comment] 2021-07-31 06:08
I tried using Attribute* from Windows.Foundation.Metadata and it didn't work either

**Comment by angelazhangmsft** [comment] 2021-08-02 16:49
Is this a duplicate of of #370?

**Comment by asklar** [comment] 2021-08-02 20:06
It looks like they're at least related - the MIDL thing is a symptom of the metadata not being written

**Comment by angelazhangmsft** [comment] 2021-08-23 21:25
Closing this issue and tracking with #370.

**Closed by angelazhangmsft** 2021-08-23 21:25 UTC
Labels: bug, authoring, cswinmd
