### ISSUE TITLE
System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.' in 2.1.1 Version

### ISSUE THREAD

**Issue by nextcodelab** [microsoft/CsWinRT#1715] opened 2024-08-10 10:21 UTC
**Describe the bug**  
When using `Microsoft.Windows.CsWinRT` version 2.1.1 in a WinUI project, even simple method calls or operations result in a `System.Reflection.TargetInvocationException` with an inner `NotSupportedException` stating "Managed vtable types (i.e., containing any reference types) are not supported." Reverting to version 2.0.7 resolves the issue.

**To Reproduce**  
1. Create a WinUI project.
2. Add the `Microsoft.Windows.CsWinRT` package version 2.1.1.
3. Implement a simple method, such as:

    ```csharp
    public static async Task<StorageFolder> GetWallpaperFolder()
    {
        return await StorageHelper.LocalFolder.CreateFolderAsync("wallpapers", CreationCollisionOption.OpenIfExists);
    }
    ```

4. Attempt to run the project.
5. Observe that the above method (or similar simple methods) throws a `System.Reflection.TargetInvocationException`.

**Expected behavior**  
The project should run without exceptions, and simple method calls should execute as expected, similar to the behavior with version 2.0.7 of `Microsoft.Windows.CsWinRT`.

**Version Info**  
- **CsWinRT NuGet Package:** 2.1.1 (Issue occurs)
- **CsWinRT NuGet Package:** 2.0.7 (Working)
- **.NET SDK:** [Specify your version, e.g., 6.0.100]
- **Windows SDK:** 10.0.22621.2428
- **WinUI Version:** net6.0-windows10.0.19041.0, TargetPlatformMinVersion 10.0.17763.0

**Additional context**  
The issue seems to be related to changes in how version 2.1.1 of `Microsoft.Windows.CsWinRT` handles managed vtable types, leading to widespread exceptions in the project. Reverting to version 2.0.7 resolves the problem entirely.

**Comment by dongle-the-gadget** [comment] 2024-08-10 11:59
Duplicate of #1713

**Comment by manodasanW** [comment] 2024-08-10 17:04
See https://github.com/microsoft/CsWinRT/issues/1713#issuecomment-2278143205

**Comment by manodasanW** [comment] 2024-08-26 21:55
Let me know if you still run into this with the updated Windows SDK projection being used via `WindowsSdkPackageVersion`.  The updated versions are also now in the upcoming .NET SDK servicing build so explicitly specifying it will only be needed until that is out.

**Closed by manodasanW** 2024-08-26 21:55 UTC
Labels: bug
