### ISSUE TITLE
ProjectReference to interop project causes build error

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/CsWinRT#628] opened 2020-12-09 01:17 UTC
I have a C# app which has a project reference to an interop project. This causes the following build error:

3>C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(934,5): error NETSDK1130: Referencing a Windows Metadata component directly when targeting .NETCoreApp,Version=v5.0 is not supported. Use the C#/WinRT projection tool (https://aka.ms/cswinrt) or a provided projection for this target.
3>Done building project "WinUIClassLibrary.csproj" -- FAILED.

Adding nuget references to `Microsoft.Windows.CsWinRT` fixes the issue, but I wouldn't expect that I need to do that, since I'm just referencing a .NET5 project.

Repro project: [CS-Desktop2.zip](https://github.com/microsoft/CsWinRT/files/5662908/CS-Desktop2.zip)

/cc @angelazhangmsft

**Comment by stevenbrix** [comment] 2020-12-09 01:24
And since pictures are worth a 1000 words, here is the project configuration:
![image](https://user-images.githubusercontent.com/9649518/101561429-2edd9900-397a-11eb-91c3-5d7d5a7b8c6e.png)

**Comment by Scottj1s** [comment] 2020-12-09 19:50
The issue is with the RuntimeComponent1.Interop project publishing out its winmd file to the referencing project.  We have an issue tracking that somewhere for nugetized components (props and targets sensing the referencing target and publishing out either native dll/winmd OR managed interop dll).  But in a direct project reference scenario, you'd need to take care of that yourself.  Adding the cswinrt nuget reference provides the convenience of disabling all winmd references (itself a workaround to prevent NETSDK1130 errors)

**Comment by Scottj1s** [comment] 2020-12-09 20:01
This is yet another example of why the current implementation of NETSDK1130 enforcement (via _BlockWinMDsOnUnsupportedTFMs) should be reconsidered - too many false positives.  

See also:
[New winmd reference enforcement takes down unit test host
](https://github.com/dotnet/sdk/issues/12087)
[New winmd reference enforcement targets wrong items](https://github.com/dotnet/sdk/issues/13233)
[Compilation fails with NETSDK1130 error, WITHOUT directly referencing a winmd](https://github.com/dotnet/sdk/issues/14267)

**Comment by Scottj1s** [comment] 2020-12-11 19:53
closing, as not a cswinrt issue

**Closed by Scottj1s** 2020-12-11 19:53 UTC
