### ISSUE TITLE
netstandard2.0 library based on Microsoft.Windows.SDK.Net cannot be referenced from UWP

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/CsWinRT#290] opened 2020-05-23 18:15 UTC
I created a `netstandard2.0` library using the `Windows.Devices.Bluetooth` APIs via the `Microsoft.Windows.SDK.NET` nuget package. When I referenced it from an UWP head project, I got errors like:

```
The type 'LaunchActivatedEventArgs' exists in both 'Microsoft.Windows.SDK.NET, Version=10.0.18362.3, Culture=neutral, PublicKeyToken=null' and 'Windows.Foundation.UniversalApiContract, Version=8.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'
```

I use:
- Visual Studio 16.7 Preview 1
UWP project:
- targeting build 18362
- `Microsoft.NETCore.UniversalWindowsPlatform` version 6.2.10

Library:
- targeting `netstandard2.0`
- `Microsoft.Windows.SDK.NET` version 10.0.18362.3-preview

**Comment by hansmbakker** [comment] 2020-05-23 19:28
Using the older `Microsoft.Windows.SDK.Contracts` I get errors
- with EventHandler like
```
Property, indexer, or event 'DeviceWatcher.Added' is not supported by the language; try directly calling accessor methods 'DeviceWatcher.add_Added(TypedEventHandler<DeviceWatcher, DeviceInformation>)' or 'DeviceWatcher.remove_Added(EventRegistrationToken)'
```
- An assembly with the same simple name 'Windows.System.SystemManagementContract' has already been imported. Try removing one of the references (e.g. 'C:\Users\xxxxx\.nuget\packages\microsoft.windows.sdk.contracts\10.0.19041.1\ref\netstandard2.0\Windows.System.SystemManagementContract.winmd') or sign them to enable side-by-side.	
```

**Comment by hansmbakker** [comment] 2020-05-29 16:51
@Scottj1s could you say something about this?

**Comment by mqudsi** [comment] 2020-05-30 23:21
This blocks using WinRT APIs in .NET Core WPF projects using Microsoft.Toolkit.Wpf.UI and co.

**Comment by AdamBraden** [comment] 2020-05-31 07:11
@hansmbakker - can you clarify your scenario? NetStandard does not support WinRT types, so you cannot pass winrt types as parameters or return them from the method call. If you want to expose winrt types then you must create a WinRT component. WinRT components can be called from netfx & netcore3+ apps. 

The NetStandard2 support in CSWinRT is for platforms that currently do not support WinRT types - eg: mono/unity. I would expect netstandard2 libraries and netcore3 apps to use the Contracts package.

**Comment by hansmbakker** [comment] 2020-05-31 16:37
@AdamBraden my goal (regardless of whether to use `Microsoft.Windows.SDK.NET` or `Microsoft.Windows.SDK.Contracts`) is:
to create a library for a bluetooth device that can be used both by a desktop app and a UWP app. The structure I am trying to achieve is as follows:
![image](https://user-images.githubusercontent.com/3463496/83350420-43423880-a33c-11ea-9e60-a7358367f1ff.png)

The Netstandard2.0 library should expose methods and events, but I believe the netstandard2.0 library does not need to expose WinRT types.

The issue is that, with the shown setup, I get a lot of errors. As mentioned, with `Microsoft.Windows.SDK.NET` the compiler thinks that types are defined twice, and with `Microsoft.Windows.SDK.Contracts` I get other compiler errors.

**Comment by manodasanW** [comment] 2020-06-01 01:31
@hansmbakker I was able to repro most of the issues you mention.  Given your library needs to be able to be referenced by UWP projects, I would suggest using the `Microsoft.Windows.SDK.Contracts` package as Adam mentions because the `Microsoft.Windows.SDK.NET` package distributes the same types in the UWP package and thereby causing the conflicts you see.

With regards to the event handler not supported by language error you see when using the `Microsoft.Windows.SDK.Contracts` package, you should be able to resolve that by adding a reference in your library to the [`System.Runtime.InteropServices.WindowsRuntime package`](https://www.nuget.org/packages/System.Runtime.InteropServices.WindowsRuntime/4.3.0).  Adding a reference to that package seems to allow the event language syntax to be recognized.

In regards to your other error with double references to the `SystemManagementContract`, I haven't been able to repro it.  Can you provide a sample with a repro after resolving the other error and are you able to tell where the 2nd reference comes from?

**Comment by hansmbakker** [comment] 2020-06-01 10:05
@manodasanW thank you for your explanation! I will try your suggestions and come back when I can say more.

> because the Microsoft.Windows.SDK.NET package distributes the same types as the UWP project
will this be fixed at a later moment? Or will UWP projects start using the `Microsoft.Windows.SDK.NET` package later?

**Comment by hansmbakker** [comment] 2020-06-01 10:23
@manodasanW thank you for your explanation! I tried your suggestion.
- the event handler issue was fixed indeed by using `System.Runtime.InteropServices.WindowsRuntime`. Is there some documentation about that besides [this page](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.windowsruntime.eventregistrationtoken?view=netcore-3.1)? Like an overview of things one can encounter when creating such a library and using WinRT code in it?
- The double reference errors are still there unfortunately. I created a [repro repository](https://github.com/hansmbakker/winsdkcontracts-bugrepro) for it, but it is not clear to me why it gives these errors.

One more question:
> because the `Microsoft.Windows.SDK.NET` package distributes the same types as the UWP project

will this be fixed at a later moment? Or will UWP projects start using the `Microsoft.Windows.SDK.NET` package later?

**Comment by manodasanW** [comment] 2020-06-02 04:33
@hansmbakker thanks for the repro.  I was able to reproduce your issue.  It looks like the winmd types from the `Microsoft.Windows.SDK.Contracts` package consumed by your library is visible to the UWP project and that causes a conflict with the same types already available in it.  When I was previously trying to repro it, my UWP project was targeting the same version as the contracts package I used in the .NET library causing for the duplicate references to be automatically resolved.  In your case, they are actually targeting different versions and that ends up in a conflict not being able to decide which version to use.

Given that the contracts package is used only for building your .NET library and your library doesn't  expose WinRT types from it, I believe you should be able to declare the content of the contracts package as a [private asset](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets) which is used only for building your library and that would prevent it from being visible to the UWP project and should unblock you.  Let me know if that works.  Something like the following in the csproj for your library should address it:

```
<PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.19041.1>
  <PrivateAssets>all</PrivateAssets>
</PackageReference>
```

> Is there some documentation about that besides [this page](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.windowsruntime.eventregistrationtoken?view=netcore-3.1)? Like an overview of things one can encounter when creating such a library and using WinRT code in it?

I agree we need some documentation for developing with the contracts package with tips containing both this information and the details from the above issue.  I will bring this up with the appropriate folks.  But I also think the contracts package should probably take a dependency on `System.Runtime.InteropServices.WindowsRuntime` package which I will look into for future versions of it.

> will this be fixed at a later moment? Or will UWP projects start using the `Microsoft.Windows.SDK.NET` package later?

We haven't decided yet whether the `Microsoft.Windows.SDK.NET` package will be available for use in UWP projects or not as they already have WinMD support and are still evaluating it.  If you do believe there is a scenario that needs it that the contracts package doesn't address, do let me know as it would be valuable input.

**Comment by hansmbakker** [comment] 2020-06-02 17:54
@manodasanW that private assets workaround helped, thank you!

> I will bring this up with the appropriate folks

Thank you!

> But I also think the contracts package should probably take a dependency on `System.Runtime.InteropServices.WindowsRuntime` package

Agreed, it would make this scenario "just work". I ran into this issue with Event Handler compatibility before and didn't know how to solve it then.

> If you do believe there is a scenario that needs it that the contracts package doesn't address, do let me know

I think there is value in the possibility of writing libraries and (WinUI3) controls that can be referenced both from UWP and Win32 projects, like the dependency structure I shared a drawing of.

Given that the WinMD support will be removed from the compilers, eventually Win32 will not work anymore with `Microsoft.Windows.SDK.Contracts` (the reason for Microsoft creating `Microsoft.Windows.SDK.Net`).

In that case, I would not want my logic or control library to be required to reference both  `Microsoft.Windows.SDK.*` packages, and I would like it if  `Microsoft.Windows.SDK.Net` could be referenced from all project types.

**Comment by angelazhangmsft** [comment] 2021-11-23 23:20
@hansmbakker - you could try the new embedded support (#304) which allows you to compile the SDK projection types and runtime sources into your library output and remove the runtime/projection dependencies. We have not tested this with a UWP app, but theoretically it should work.

Here are the [embedded docs](https://github.com/microsoft/CsWinRT/blob/master/docs/embedded.md).

However, we don't have plans for UWP-specific work so I am closing this issue.

**Closed by angelazhangmsft** 2021-11-23 23:20 UTC
Labels: documentation
